import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <-- generated by `flutterfire configure`
import 'services/firebase_service.dart';
import 'router/app_router.dart';
import 'theme/app_theme.dart';

void main() async {
  // Make sure Flutter is ready before we use any plugins.
  WidgetsFlutterBinding.ensureInitialized();

  // Connect this app to your Firebase project.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Fill the database with sample data the FIRST time only.
  // Wrapped in try/catch so the app still opens even if seeding fails
  // (for example before the Firestore security rules are set).
  try {
    await FirebaseService().seedSampleDataIfEmpty();
  } catch (e) {
    debugPrint('Sample data seeding skipped: $e');
  }

  runApp(const ProviderScope(child: ExhibitionApp()));
}

class ExhibitionApp extends ConsumerWidget {
  const ExhibitionApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    return MaterialApp.router(
      title: 'Exhibition Booth Management',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      routerConfig: router,
      debugShowCheckedModeBanner: false,
    );
  }
}
